<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Tp_Investigacion_NLP_Web</RootNamespace>
    <UserSecretsId>tp-investigacion-nlp-web-2026</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tp-Investigacion-NLP-Entidades\Tp-Investigacion-NLP-Entidades.csproj" />
    <ProjectReference Include="..\Tp-Investigacion-NLP-Logica\Tp-Investigacion-NLP-Logica.csproj" />
  </ItemGroup>

</Project>
