// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tp_Investigacion_NLP_Entidades;

#nullable disable

namespace Tp_Investigacion_NLP_Entidades.Migrations
{
    [DbContext(typeof(NLPDbContext))]
    [Migration("20260626173745_CreacionTablasEInicializacionDeDatos")]
    partial class CreacionTablasEInicializacionDeDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuracionAnios")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniversidadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadId");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DuracionAnios = 3,
                            Nombre = "Tecnicatura en Desarrollo Web",
                            UniversidadId = 1
                        },
                        new
                        {
                            Id = 2,
                            DuracionAnios = 5,
                            Nombre = "Ingeniería en Informática",
                            UniversidadId = 1
                        },
                        new
                        {
                            Id = 3,
                            DuracionAnios = 4,
                            Nombre = "Licenciatura en Administración",
                            UniversidadId = 1
                        },
                        new
                        {
                            Id = 4,
                            DuracionAnios = 5,
                            Nombre = "Ingeniería en Sistemas",
                            UniversidadId = 2
                        },
                        new
                        {
                            Id = 5,
                            DuracionAnios = 6,
                            Nombre = "Medicina",
                            UniversidadId = 2
                        },
                        new
                        {
                            Id = 6,
                            DuracionAnios = 5,
                            Nombre = "Derecho",
                            UniversidadId = 2
                        });
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Conversacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Conversaciones");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Correlativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MateriaCorrelativaId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaCorrelativaId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Correlativas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MateriaCorrelativaId = 1,
                            MateriaId = 2
                        },
                        new
                        {
                            Id = 2,
                            MateriaCorrelativaId = 2,
                            MateriaId = 3
                        },
                        new
                        {
                            Id = 3,
                            MateriaCorrelativaId = 2,
                            MateriaId = 4
                        },
                        new
                        {
                            Id = 4,
                            MateriaCorrelativaId = 4,
                            MateriaId = 5
                        },
                        new
                        {
                            Id = 5,
                            MateriaCorrelativaId = 5,
                            MateriaId = 6
                        },
                        new
                        {
                            Id = 6,
                            MateriaCorrelativaId = 7,
                            MateriaId = 9
                        },
                        new
                        {
                            Id = 7,
                            MateriaCorrelativaId = 9,
                            MateriaId = 10
                        },
                        new
                        {
                            Id = 8,
                            MateriaCorrelativaId = 9,
                            MateriaId = 11
                        },
                        new
                        {
                            Id = 9,
                            MateriaCorrelativaId = 11,
                            MateriaId = 12
                        },
                        new
                        {
                            Id = 10,
                            MateriaCorrelativaId = 13,
                            MateriaId = 15
                        },
                        new
                        {
                            Id = 11,
                            MateriaCorrelativaId = 15,
                            MateriaId = 16
                        },
                        new
                        {
                            Id = 12,
                            MateriaCorrelativaId = 16,
                            MateriaId = 17
                        },
                        new
                        {
                            Id = 13,
                            MateriaCorrelativaId = 17,
                            MateriaId = 18
                        },
                        new
                        {
                            Id = 14,
                            MateriaCorrelativaId = 19,
                            MateriaId = 21
                        },
                        new
                        {
                            Id = 15,
                            MateriaCorrelativaId = 21,
                            MateriaId = 22
                        },
                        new
                        {
                            Id = 16,
                            MateriaCorrelativaId = 22,
                            MateriaId = 23
                        },
                        new
                        {
                            Id = 17,
                            MateriaCorrelativaId = 23,
                            MateriaId = 24
                        },
                        new
                        {
                            Id = 18,
                            MateriaCorrelativaId = 25,
                            MateriaId = 27
                        },
                        new
                        {
                            Id = 19,
                            MateriaCorrelativaId = 27,
                            MateriaId = 28
                        },
                        new
                        {
                            Id = 20,
                            MateriaCorrelativaId = 28,
                            MateriaId = 29
                        },
                        new
                        {
                            Id = 21,
                            MateriaCorrelativaId = 29,
                            MateriaId = 30
                        },
                        new
                        {
                            Id = 22,
                            MateriaCorrelativaId = 31,
                            MateriaId = 33
                        },
                        new
                        {
                            Id = 23,
                            MateriaCorrelativaId = 32,
                            MateriaId = 34
                        },
                        new
                        {
                            Id = 24,
                            MateriaCorrelativaId = 33,
                            MateriaId = 35
                        },
                        new
                        {
                            Id = 25,
                            MateriaCorrelativaId = 35,
                            MateriaId = 36
                        });
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("int");

                    b.Property<bool>("EsOptativa")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.ToTable("Materia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 1,
                            CarreraId = 1,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Introducción a la Programación"
                        },
                        new
                        {
                            Id = 2,
                            Anio = 1,
                            CarreraId = 1,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Programación I"
                        },
                        new
                        {
                            Id = 3,
                            Anio = 2,
                            CarreraId = 1,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Bases de Datos"
                        },
                        new
                        {
                            Id = 4,
                            Anio = 2,
                            CarreraId = 1,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Programación Web I"
                        },
                        new
                        {
                            Id = 5,
                            Anio = 3,
                            CarreraId = 1,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Programación Web II"
                        },
                        new
                        {
                            Id = 6,
                            Anio = 3,
                            CarreraId = 1,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Programación Web III"
                        },
                        new
                        {
                            Id = 7,
                            Anio = 1,
                            CarreraId = 2,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Álgebra"
                        },
                        new
                        {
                            Id = 8,
                            Anio = 1,
                            CarreraId = 2,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Análisis Matemático I"
                        },
                        new
                        {
                            Id = 9,
                            Anio = 1,
                            CarreraId = 2,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Programación"
                        },
                        new
                        {
                            Id = 10,
                            Anio = 2,
                            CarreraId = 2,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Arquitectura de Computadoras"
                        },
                        new
                        {
                            Id = 11,
                            Anio = 2,
                            CarreraId = 2,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Bases de Datos"
                        },
                        new
                        {
                            Id = 12,
                            Anio = 4,
                            CarreraId = 2,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Inteligencia Artificial"
                        },
                        new
                        {
                            Id = 13,
                            Anio = 1,
                            CarreraId = 3,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Administración I"
                        },
                        new
                        {
                            Id = 14,
                            Anio = 1,
                            CarreraId = 3,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Contabilidad"
                        },
                        new
                        {
                            Id = 15,
                            Anio = 2,
                            CarreraId = 3,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Economía"
                        },
                        new
                        {
                            Id = 16,
                            Anio = 2,
                            CarreraId = 3,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Marketing"
                        },
                        new
                        {
                            Id = 17,
                            Anio = 3,
                            CarreraId = 3,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Finanzas"
                        },
                        new
                        {
                            Id = 18,
                            Anio = 4,
                            CarreraId = 3,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Gestión Estratégica"
                        },
                        new
                        {
                            Id = 19,
                            Anio = 1,
                            CarreraId = 4,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Algoritmos"
                        },
                        new
                        {
                            Id = 20,
                            Anio = 1,
                            CarreraId = 4,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Matemática Discreta"
                        },
                        new
                        {
                            Id = 21,
                            Anio = 2,
                            CarreraId = 4,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Programación Avanzada"
                        },
                        new
                        {
                            Id = 22,
                            Anio = 2,
                            CarreraId = 4,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Bases de Datos"
                        },
                        new
                        {
                            Id = 23,
                            Anio = 3,
                            CarreraId = 4,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Redes"
                        },
                        new
                        {
                            Id = 24,
                            Anio = 4,
                            CarreraId = 4,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Ingeniería de Software"
                        },
                        new
                        {
                            Id = 25,
                            Anio = 1,
                            CarreraId = 5,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Anatomía"
                        },
                        new
                        {
                            Id = 26,
                            Anio = 1,
                            CarreraId = 5,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Histología"
                        },
                        new
                        {
                            Id = 27,
                            Anio = 2,
                            CarreraId = 5,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Fisiología"
                        },
                        new
                        {
                            Id = 28,
                            Anio = 3,
                            CarreraId = 5,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Patología"
                        },
                        new
                        {
                            Id = 29,
                            Anio = 4,
                            CarreraId = 5,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Farmacología"
                        },
                        new
                        {
                            Id = 30,
                            Anio = 5,
                            CarreraId = 5,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Clínica Médica"
                        },
                        new
                        {
                            Id = 31,
                            Anio = 1,
                            CarreraId = 6,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Introducción al Derecho"
                        },
                        new
                        {
                            Id = 32,
                            Anio = 1,
                            CarreraId = 6,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Derecho Civil"
                        },
                        new
                        {
                            Id = 33,
                            Anio = 2,
                            CarreraId = 6,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Derecho Penal"
                        },
                        new
                        {
                            Id = 34,
                            Anio = 2,
                            CarreraId = 6,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Derecho Constitucional"
                        },
                        new
                        {
                            Id = 35,
                            Anio = 3,
                            CarreraId = 6,
                            Cuatrimestre = 2,
                            EsOptativa = false,
                            Nombre = "Derecho Laboral"
                        },
                        new
                        {
                            Id = 36,
                            Anio = 5,
                            CarreraId = 6,
                            Cuatrimestre = 1,
                            EsOptativa = false,
                            Nombre = "Derecho Internacional"
                        });
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Universidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acronimo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Universidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acronimo = "UNLAM",
                            Ciudad = "San Justo",
                            Nombre = "Universidad Nacional de La Matanza",
                            Pais = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Acronimo = "UBA",
                            Ciudad = "Buenos Aires",
                            Nombre = "Universidad de Buenos Aires",
                            Pais = "Argentina"
                        });
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Carrera", b =>
                {
                    b.HasOne("Tp_Investigacion_NLP_Entidades.Universidad", "Universidad")
                        .WithMany("Carreras")
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Conversacion", b =>
                {
                    b.HasOne("Tp_Investigacion_NLP_Entidades.Usuario", "Usuario")
                        .WithMany("Conversaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Correlativa", b =>
                {
                    b.HasOne("Tp_Investigacion_NLP_Entidades.Materia", "MateriaCorrelativa")
                        .WithMany("EsCorrelativaDe")
                        .HasForeignKey("MateriaCorrelativaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tp_Investigacion_NLP_Entidades.Materia", "Materia")
                        .WithMany("Correlativas")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("MateriaCorrelativa");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Materia", b =>
                {
                    b.HasOne("Tp_Investigacion_NLP_Entidades.Carrera", "Carrera")
                        .WithMany("Materias")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Mensaje", b =>
                {
                    b.HasOne("Tp_Investigacion_NLP_Entidades.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Carrera", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Conversacion", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Materia", b =>
                {
                    b.Navigation("Correlativas");

                    b.Navigation("EsCorrelativaDe");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Universidad", b =>
                {
                    b.Navigation("Carreras");
                });

            modelBuilder.Entity("Tp_Investigacion_NLP_Entidades.Usuario", b =>
                {
                    b.Navigation("Conversaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
